# Generated by Django 4.2 on 2026-02-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_duration', models.FloatField()),
                ('total_fwd_packets', models.FloatField()),
                ('total_bwd_packets', models.FloatField()),
                ('fwd_pkt_len_mean', models.FloatField()),
                ('bwd_pkt_len_mean', models.FloatField()),
                ('pkt_len_variance', models.FloatField()),
                ('predicted_attack', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
